server:
  port: 8081

spring:
  application:
    name: user-service
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: {GOOGLE_CLIENT_ID}
            client-secret: {GOOGLE_CLIENT_SECRET}
            redirect-uri: http://localhost:3000/oauth2/callback
            scope:
              - openid
              - email
              - profile
  jpa:
    properties:
      hibernate:
        default_schema: user_service
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: validate
  cloud:
    config:
      enabled: false
  euraka:
    client:
      enabled: false

jwt:
  secret: a-string-secret-at-least-256-bits-long-a-string-secret-at-least-256-bits

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: "health, info, metrics"