--liquibase formatted sql

--changeset lain:1
CREATE SCHEMA user_service;

CREATE TABLE user_service.users
(
    id            BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username      VARCHAR(64) UNIQUE  NOT NULL,
    password      VARCHAR(255)        NOT NULL,
    email         VARCHAR(128) UNIQUE NOT NULL,
    date_of_birth DATE                NOT NULL CHECK (date_of_birth >= DATE '1900-01-01' AND date_of_birth <= CURRENT_DATE),
    role          VARCHAR(20) DEFAULT 'USER',
    created_at    TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP   DEFAULT CURRENT_TIMESTAMP
);

--changeset lain:2
CREATE TABLE user_service.user_provider
(
    id               BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id          BIGINT       NOT NULL REFERENCES user_service.users (id) ON DELETE CASCADE,
    provider         VARCHAR(32)  NOT NULL,
    provider_user_id VARCHAR(255) NOT NULL,
    UNIQUE (provider, provider_user_id)
);